import { IpsumCard } from '../interfaces/lerom-card.interface';

export const IpsumContentContent: IpsumCard[] = [
    {
        id: 1,
        name: "Don hart",
        age: 30,
        leftLabelName: "Location",
        leftLabelValue: "Seattle",
        rightLabelName: "Ipsum",
        rightLabelValue: "$ 125 (25/ea)",
        preferenceProfile: "15.54% (below avg options) (20%)",
        expand: true,
        preferenceSummary: "34 2b 34 2w 36 2h Lorem 96+ Ipsum 90+ Dolor 70+",
        profileSummary: "Masters EU Ivy League $500k 20 employees Soccer Scholarship Wrestling States",
        weightHeight: "56- kg / 160- cm",
        loremIpsumDolor: "Assertive",
        loremIpsum: "Lorem, Ipsum, Dolor",
        loremIpsumOne: 30,
        loremIpsumTwo: "$1876(~27 / ea)",
        loremIpsumthree: "01-03-23 (1.2 years)",
        loremIpsumFour: "7.4 / 6.1+",
        loremIpsumFive: "5"
    },
    {
        id: 2,
        name: "Don hart",
        age: 30,
        leftLabelName: "Location",
        leftLabelValue: "Seattle",
        rightLabelName: "Ipsum",
        rightLabelValue: "$ 125 (25/ea)",
        preferenceProfile: "15.54% (below avg options) (20%)",
        expand: true,
        preferenceSummary: "34 2b 34 2w 36 2h Lorem 96+ Ipsum 90+ Dolor 70+",
        profileSummary: "Masters EU Ivy League $500k 20 employees Soccer Scholarship Wrestling States",
        weightHeight: "56- kg / 160- cm",
        loremIpsumDolor: "Assertive",
        loremIpsum: "Lorem, Ipsum, Dolor",
        loremIpsumOne: 30,
        loremIpsumTwo: "$1876(~27 / ea)",
        loremIpsumthree: "01-03-23 (1.2 years)",
        loremIpsumFour: "7.4 / 6.1+",
        loremIpsumFive: "5"
    },
    {
        id: 3,
        name: "Don hart",
        age: 30,
        leftLabelName: "Location",
        leftLabelValue: "Seattle",
        rightLabelName: "Ipsum",
        rightLabelValue: "$ 125 (25/ea)",
        preferenceProfile: "15.54% (below avg options) (20%)",
        expand: true,
        preferenceSummary: "34 2b 34 2w 36 2h Lorem 96+ Ipsum 90+ Dolor 70+",
        profileSummary: "Masters EU Ivy League $500k 20 employees Soccer Scholarship Wrestling States",
        weightHeight: "56- kg / 160- cm",
        loremIpsumDolor: "Assertive",
        loremIpsum: "Lorem, Ipsum, Dolor",
        loremIpsumOne: 30,
        loremIpsumTwo: "$1876(~27 / ea)",
        loremIpsumthree: "01-03-23 (1.2 years)",
        loremIpsumFour: "7.4 / 6.1+",
        loremIpsumFive: "5"
    },

]
